apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-server1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-server1
  template:
    metadata:
      labels:
        app: node-app-server1
    spec:
      containers:
        - name: node-app-server1
          image: my-node-app-server1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
