apiVersion: v1
kind: Service
metadata:
  name: node-app-server1-service
spec:
  type: NodePort
  selector:
    app: node-app-server1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080 # You can specify a port or let Kubernetes assign one
